# Generated by Django 4.2.21 on 2025-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Patient weight in kg', max_digits=5, null=True),
        ),
    ]
