# Generated by Django 4.2.21 on 2025-05-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='foot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.foottype'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.prescriptionstatus'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescriptions.template'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='wear_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.weartime'),
        ),
        migrations.AddField(
            model_name='posting',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='plantermodifier',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planter_modifier', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='offloading',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='off_loading', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='materialselection',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_selection', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='intrinsicadjustment',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_adjustments', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='deviceoption',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_options', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='clinicalmeasure',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_measures', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='prescriptions.prescription'),
        ),
    ]
