--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12
-- Dumped by pg_dump version 15.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices_invoice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices_invoice (
    id uuid NOT NULL,
    invoice_number character varying(50) NOT NULL,
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    due_date date NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.invoices_invoice OWNER TO postgres;

--
-- Name: invoices_invoiceitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices_invoiceitem (
    id uuid NOT NULL,
    description character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    invoice_id uuid NOT NULL,
    CONSTRAINT invoices_invoiceitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.invoices_invoiceitem OWNER TO postgres;

--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order (
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.orders_order OWNER TO postgres;

--
-- Name: orders_order_prescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_order_prescriptions (
    id bigint NOT NULL,
    order_id uuid NOT NULL,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.orders_order_prescriptions OWNER TO postgres;

--
-- Name: orders_order_prescriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_order_prescriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_prescriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients_patient (
    id uuid NOT NULL,
    external_id character varying(100),
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    date_of_birth date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    clinic_id uuid NOT NULL,
    gender character varying(10) NOT NULL
);


ALTER TABLE public.patients_patient OWNER TO postgres;

--
-- Name: prescriptions_activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_activity (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prescriptions_activity OWNER TO postgres;

--
-- Name: prescriptions_attachment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_attachment (
    id uuid NOT NULL,
    file character varying(100) NOT NULL,
    filename character varying(255) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_attachment OWNER TO postgres;

--
-- Name: prescriptions_clinicalmeasure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_clinicalmeasure (
    id uuid NOT NULL,
    left_scan_angle double precision,
    left_forefoot_varus double precision,
    left_forefoot_valgus double precision,
    left_heel_to_mpj_centre double precision,
    left_posterior_heel_to_heel_centre double precision,
    right_scan_angle double precision,
    right_forefoot_varus double precision,
    right_forefoot_valgus double precision,
    right_heel_to_mpj_centre double precision,
    right_posterior_heel_to_heel_centre double precision,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_clinicalmeasure OWNER TO postgres;

--
-- Name: prescriptions_deviceoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_deviceoption (
    id uuid NOT NULL,
    medial_arch_height double precision,
    lateral_arch_height double precision,
    medial_heel_height double precision,
    lateral_heel_height double precision,
    heel_width double precision,
    midfoot_width double precision,
    forefoot_width double precision,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_deviceoption OWNER TO postgres;

--
-- Name: prescriptions_foottype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_foottype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prescriptions_foottype OWNER TO postgres;

--
-- Name: prescriptions_foottype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescriptions_foottype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_foottype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions_intrinsicadjustment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_intrinsicadjustment (
    id uuid NOT NULL,
    left_arch_expansion character varying(20) NOT NULL,
    left_heel_expansion character varying(20) NOT NULL,
    left_shell_width character varying(20) NOT NULL,
    left_shell_length character varying(20) NOT NULL,
    left_pfa_height character varying(20) NOT NULL,
    left_pfa_value_mm double precision,
    left_skive character varying(20) NOT NULL,
    left_skive_method character varying(20),
    left_skive_depth_mm double precision,
    left_skive_degree double precision,
    left_skive_inclination character varying(20),
    left_skive_specific_inclination double precision,
    right_arch_expansion character varying(20) NOT NULL,
    right_heel_expansion character varying(20) NOT NULL,
    right_shell_width character varying(20) NOT NULL,
    right_shell_length character varying(20) NOT NULL,
    right_pfa_height character varying(20) NOT NULL,
    right_pfa_value_mm double precision,
    right_skive character varying(20) NOT NULL,
    right_skive_method character varying(20),
    right_skive_depth_mm double precision,
    right_skive_degree double precision,
    right_skive_inclination character varying(20),
    right_skive_specific_inclination double precision,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_intrinsicadjustment OWNER TO postgres;

--
-- Name: prescriptions_materialselection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_materialselection (
    id uuid NOT NULL,
    shell_material character varying(20) NOT NULL,
    shell_thickness character varying(10) NOT NULL,
    top_cover character varying(30) NOT NULL,
    second_cover character varying(30) NOT NULL,
    third_cover character varying(30) NOT NULL,
    full_length_plantar_cover character varying(20) NOT NULL,
    cover_length character varying(10) NOT NULL,
    extension_forefoot boolean NOT NULL,
    extension_midfoot_medial boolean NOT NULL,
    extension_midfoot_lateral boolean NOT NULL,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_materialselection OWNER TO postgres;

--
-- Name: prescriptions_offloading; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_offloading (
    id integer NOT NULL,
    prescription_id uuid,
    metatarsal_dome boolean DEFAULT false NOT NULL,
    metatarsal_bar boolean DEFAULT false NOT NULL,
    morton_extension boolean DEFAULT false NOT NULL,
    kinetic_wedge boolean DEFAULT false NOT NULL,
    lateral_wedge boolean DEFAULT false NOT NULL,
    medial_wedge boolean DEFAULT false NOT NULL,
    heel_skive boolean DEFAULT false NOT NULL,
    heel_aperture boolean DEFAULT false NOT NULL,
    custom_notes text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.prescriptions_offloading OWNER TO postgres;

--
-- Name: prescriptions_offloading_new_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.prescriptions_offloading_new_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.prescriptions_offloading_new_id_seq OWNER TO postgres;

--
-- Name: prescriptions_offloading_new_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.prescriptions_offloading_new_id_seq OWNED BY public.prescriptions_offloading.id;


--
-- Name: prescriptions_plantermodifier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_plantermodifier (
    id uuid NOT NULL,
    left_y_rib double precision,
    left_k_rib double precision,
    left_cuboid_modifier double precision,
    left_styloid_modifier double precision,
    left_navicular_modifier double precision,
    left_fifth_ray_modifier double precision,
    right_y_rib double precision,
    right_k_rib double precision,
    right_cuboid_modifier double precision,
    right_styloid_modifier double precision,
    right_navicular_modifier double precision,
    right_fifth_ray_modifier double precision,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_plantermodifier OWNER TO postgres;

--
-- Name: prescriptions_posting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_posting (
    id uuid NOT NULL,
    left_heel_post_width character varying(20) NOT NULL,
    left_heel_post_angle double precision,
    left_heel_post_pitch double precision,
    left_heel_post_raise double precision,
    left_heel_post_taper double precision,
    left_forefoot_post_width character varying(20) NOT NULL,
    left_forefoot_post_medial boolean NOT NULL,
    left_forefoot_post_lateral boolean NOT NULL,
    left_forefoot_post_angle double precision,
    right_heel_post_width character varying(20) NOT NULL,
    right_heel_post_angle double precision,
    right_heel_post_pitch double precision,
    right_heel_post_raise double precision,
    right_heel_post_taper double precision,
    right_forefoot_post_width character varying(20) NOT NULL,
    right_forefoot_post_medial boolean NOT NULL,
    right_forefoot_post_lateral boolean NOT NULL,
    right_forefoot_post_angle double precision,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_posting OWNER TO postgres;

--
-- Name: prescriptions_prescription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_prescription (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    turnaround character varying(20) NOT NULL,
    contact_clinician boolean NOT NULL,
    confirm_before_manufacture boolean NOT NULL,
    clinician_computer_aided_design boolean NOT NULL,
    general_notes text NOT NULL,
    left_foot_notes text NOT NULL,
    right_foot_notes text NOT NULL,
    clinician_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    template_id uuid NOT NULL,
    status_id bigint,
    foot_type_id bigint,
    wear_time_id bigint,
    activity_level_id uuid
);


ALTER TABLE public.prescriptions_prescription OWNER TO postgres;

--
-- Name: prescriptions_prescriptionstatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_prescriptionstatus (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    color character varying(20) NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prescriptions_prescriptionstatus OWNER TO postgres;

--
-- Name: prescriptions_prescriptionstatus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescriptions_prescriptionstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_prescriptionstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions_scan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_scan (
    id uuid NOT NULL,
    left_foot character varying(100),
    right_foot character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_scan OWNER TO postgres;

--
-- Name: prescriptions_shoefitting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_shoefitting (
    id uuid NOT NULL,
    sizing_style character varying(20) NOT NULL,
    orthosis_size character varying(10) NOT NULL,
    to_fit_shoe character varying(255) NOT NULL,
    prescription_id uuid NOT NULL
);


ALTER TABLE public.prescriptions_shoefitting OWNER TO postgres;

--
-- Name: prescriptions_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_template (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prescriptions_template OWNER TO postgres;

--
-- Name: prescriptions_weartime; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions_weartime (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.prescriptions_weartime OWNER TO postgres;

--
-- Name: prescriptions_weartime_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescriptions_weartime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_weartime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_clinic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_clinic (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    address text NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    logo_url character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_clinic OWNER TO postgres;

--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    role character varying(10) NOT NULL,
    active boolean NOT NULL,
    clinic_id uuid
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions_offloading id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_offloading ALTER COLUMN id SET DEFAULT nextval('public.prescriptions_offloading_new_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-05-08 10:52:44.485211+00
2	contenttypes	0002_remove_content_type_name	2025-05-08 10:52:44.503166+00
3	auth	0001_initial	2025-05-08 10:52:44.651175+00
4	auth	0002_alter_permission_name_max_length	2025-05-08 10:52:44.667951+00
5	auth	0003_alter_user_email_max_length	2025-05-08 10:52:44.687697+00
6	auth	0004_alter_user_username_opts	2025-05-08 10:52:44.708589+00
7	auth	0005_alter_user_last_login_null	2025-05-08 10:52:44.7248+00
8	auth	0006_require_contenttypes_0002	2025-05-08 10:52:44.734946+00
9	auth	0007_alter_validators_add_error_messages	2025-05-08 10:52:44.749825+00
10	auth	0008_alter_user_username_max_length	2025-05-08 10:52:44.764327+00
11	auth	0009_alter_user_last_name_max_length	2025-05-08 10:52:44.778165+00
12	auth	0010_alter_group_name_max_length	2025-05-08 10:52:44.796836+00
13	auth	0011_update_proxy_permissions	2025-05-08 10:52:44.811079+00
14	auth	0012_alter_user_first_name_max_length	2025-05-08 10:52:44.824297+00
15	users	0001_initial	2025-05-08 10:52:45.027239+00
16	admin	0001_initial	2025-05-08 10:52:45.101363+00
17	admin	0002_logentry_remove_auto_add	2025-05-08 10:52:45.119869+00
18	admin	0003_logentry_add_action_flag_choices	2025-05-08 10:52:45.138325+00
19	patients	0001_initial	2025-05-08 10:52:45.169738+00
20	patients	0002_initial	2025-05-08 10:52:45.207+00
21	prescriptions	0001_initial	2025-05-08 10:52:45.832753+00
22	orders	0001_initial	2025-05-08 10:52:45.926848+00
23	invoices	0001_initial	2025-05-08 10:52:45.983236+00
24	invoices	0002_initial	2025-05-08 10:52:46.154592+00
25	invoices	0003_invoiceitem	2025-05-08 10:52:46.236201+00
26	orders	0002_remove_order_prescription_order_prescriptions	2025-05-08 10:52:46.395582+00
27	patients	0003_alter_patient_address_alter_patient_date_of_birth_and_more	2025-05-08 10:52:46.47667+00
28	patients	0004_alter_patient_external_id	2025-05-08 10:52:46.523965+00
29	patients	add_gender_field	2025-05-08 10:52:46.54954+00
30	patients	0005_merge_0004_alter_patient_external_id_add_gender_field	2025-05-08 10:52:46.560334+00
31	patients	0006_add_missing_fields	2025-05-08 10:52:46.583725+00
32	patients	0007_remove_patient_address_remove_patient_email_and_more	2025-05-08 10:52:46.640781+00
33	prescriptions	0003_add_lookup_models	2025-05-08 10:52:47.051743+00
34	prescriptions	0004_update_offloading	2025-05-08 10:52:47.192364+00
\.


--
-- Data for Name: invoices_invoice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices_invoice (id, invoice_number, amount, status, due_date, notes, created_at, updated_at, order_id, user_id) FROM stdin;
\.


--
-- Data for Name: invoices_invoiceitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices_invoiceitem (id, description, price, quantity, created_at, updated_at, invoice_id) FROM stdin;
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order (id, status, notes, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: orders_order_prescriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_order_prescriptions (id, order_id, prescription_id) FROM stdin;
\.


--
-- Data for Name: patients_patient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patients_patient (id, external_id, first_name, last_name, date_of_birth, created_at, updated_at, clinic_id, gender) FROM stdin;
\.


--
-- Data for Name: prescriptions_activity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_activity (id, name, description, "order", is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: prescriptions_attachment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_attachment (id, file, filename, uploaded_at, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_clinicalmeasure; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_clinicalmeasure (id, left_scan_angle, left_forefoot_varus, left_forefoot_valgus, left_heel_to_mpj_centre, left_posterior_heel_to_heel_centre, right_scan_angle, right_forefoot_varus, right_forefoot_valgus, right_heel_to_mpj_centre, right_posterior_heel_to_heel_centre, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_deviceoption; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_deviceoption (id, medial_arch_height, lateral_arch_height, medial_heel_height, lateral_heel_height, heel_width, midfoot_width, forefoot_width, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_foottype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_foottype (id, name, description, "order", is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: prescriptions_intrinsicadjustment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_intrinsicadjustment (id, left_arch_expansion, left_heel_expansion, left_shell_width, left_shell_length, left_pfa_height, left_pfa_value_mm, left_skive, left_skive_method, left_skive_depth_mm, left_skive_degree, left_skive_inclination, left_skive_specific_inclination, right_arch_expansion, right_heel_expansion, right_shell_width, right_shell_length, right_pfa_height, right_pfa_value_mm, right_skive, right_skive_method, right_skive_depth_mm, right_skive_degree, right_skive_inclination, right_skive_specific_inclination, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_materialselection; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_materialselection (id, shell_material, shell_thickness, top_cover, second_cover, third_cover, full_length_plantar_cover, cover_length, extension_forefoot, extension_midfoot_medial, extension_midfoot_lateral, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_offloading; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_offloading (id, prescription_id, metatarsal_dome, metatarsal_bar, morton_extension, kinetic_wedge, lateral_wedge, medial_wedge, heel_skive, heel_aperture, custom_notes, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: prescriptions_plantermodifier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_plantermodifier (id, left_y_rib, left_k_rib, left_cuboid_modifier, left_styloid_modifier, left_navicular_modifier, left_fifth_ray_modifier, right_y_rib, right_k_rib, right_cuboid_modifier, right_styloid_modifier, right_navicular_modifier, right_fifth_ray_modifier, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_posting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_posting (id, left_heel_post_width, left_heel_post_angle, left_heel_post_pitch, left_heel_post_raise, left_heel_post_taper, left_forefoot_post_width, left_forefoot_post_medial, left_forefoot_post_lateral, left_forefoot_post_angle, right_heel_post_width, right_heel_post_angle, right_heel_post_pitch, right_heel_post_raise, right_heel_post_taper, right_forefoot_post_width, right_forefoot_post_medial, right_forefoot_post_lateral, right_forefoot_post_angle, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_prescription; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_prescription (id, created_at, updated_at, turnaround, contact_clinician, confirm_before_manufacture, clinician_computer_aided_design, general_notes, left_foot_notes, right_foot_notes, clinician_id, patient_id, template_id, status_id, foot_type_id, wear_time_id, activity_level_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_prescriptionstatus; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_prescriptionstatus (id, name, description, color, "order", is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: prescriptions_scan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_scan (id, left_foot, right_foot, created_at, updated_at, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_shoefitting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_shoefitting (id, sizing_style, orthosis_size, to_fit_shoe, prescription_id) FROM stdin;
\.


--
-- Data for Name: prescriptions_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_template (id, name, description, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: prescriptions_weartime; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions_weartime (id, name, description, "order", is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: users_clinic; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_clinic (id, name, address, phone, email, logo_url, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (password, last_login, is_superuser, is_staff, is_active, date_joined, id, email, first_name, last_name, role, active, clinic_id) FROM stdin;
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 34, true);


--
-- Name: orders_order_prescriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_prescriptions_id_seq', 1, false);


--
-- Name: prescriptions_foottype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_foottype_id_seq', 1, false);


--
-- Name: prescriptions_offloading_new_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_offloading_new_id_seq', 1, false);


--
-- Name: prescriptions_prescriptionstatus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_prescriptionstatus_id_seq', 1, false);


--
-- Name: prescriptions_weartime_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_weartime_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: invoices_invoice invoices_invoice_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoice
    ADD CONSTRAINT invoices_invoice_invoice_number_key UNIQUE (invoice_number);


--
-- Name: invoices_invoice invoices_invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoice
    ADD CONSTRAINT invoices_invoice_pkey PRIMARY KEY (id);


--
-- Name: invoices_invoiceitem invoices_invoiceitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoiceitem
    ADD CONSTRAINT invoices_invoiceitem_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_order_prescriptions orders_order_prescriptio_order_id_prescription_id_a54d7eff_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order_prescriptions
    ADD CONSTRAINT orders_order_prescriptio_order_id_prescription_id_a54d7eff_uniq UNIQUE (order_id, prescription_id);


--
-- Name: orders_order_prescriptions orders_order_prescriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order_prescriptions
    ADD CONSTRAINT orders_order_prescriptions_pkey PRIMARY KEY (id);


--
-- Name: patients_patient patients_patient_external_id_57f63860_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_external_id_57f63860_uniq UNIQUE (external_id);


--
-- Name: patients_patient patients_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_activity prescriptions_activity_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_activity
    ADD CONSTRAINT prescriptions_activity_name_key UNIQUE (name);


--
-- Name: prescriptions_activity prescriptions_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_activity
    ADD CONSTRAINT prescriptions_activity_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_attachment prescriptions_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_attachment
    ADD CONSTRAINT prescriptions_attachment_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_clinicalmeasure prescriptions_clinicalmeasure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_clinicalmeasure
    ADD CONSTRAINT prescriptions_clinicalmeasure_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_clinicalmeasure prescriptions_clinicalmeasure_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_clinicalmeasure
    ADD CONSTRAINT prescriptions_clinicalmeasure_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_deviceoption prescriptions_deviceoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_deviceoption
    ADD CONSTRAINT prescriptions_deviceoption_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_deviceoption prescriptions_deviceoption_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_deviceoption
    ADD CONSTRAINT prescriptions_deviceoption_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_foottype prescriptions_foottype_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_foottype
    ADD CONSTRAINT prescriptions_foottype_name_key UNIQUE (name);


--
-- Name: prescriptions_foottype prescriptions_foottype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_foottype
    ADD CONSTRAINT prescriptions_foottype_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_intrinsicadjustment prescriptions_intrinsicadjustment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_intrinsicadjustment
    ADD CONSTRAINT prescriptions_intrinsicadjustment_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_intrinsicadjustment prescriptions_intrinsicadjustment_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_intrinsicadjustment
    ADD CONSTRAINT prescriptions_intrinsicadjustment_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_materialselection prescriptions_materialselection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_materialselection
    ADD CONSTRAINT prescriptions_materialselection_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_materialselection prescriptions_materialselection_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_materialselection
    ADD CONSTRAINT prescriptions_materialselection_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_offloading prescriptions_offloading_new_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_offloading
    ADD CONSTRAINT prescriptions_offloading_new_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_plantermodifier prescriptions_plantermodifier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_plantermodifier
    ADD CONSTRAINT prescriptions_plantermodifier_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_plantermodifier prescriptions_plantermodifier_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_plantermodifier
    ADD CONSTRAINT prescriptions_plantermodifier_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_posting prescriptions_posting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_posting
    ADD CONSTRAINT prescriptions_posting_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_posting prescriptions_posting_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_posting
    ADD CONSTRAINT prescriptions_posting_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_prescription prescriptions_prescription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescription_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_prescriptionstatus prescriptions_prescriptionstatus_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescriptionstatus
    ADD CONSTRAINT prescriptions_prescriptionstatus_name_key UNIQUE (name);


--
-- Name: prescriptions_prescriptionstatus prescriptions_prescriptionstatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescriptionstatus
    ADD CONSTRAINT prescriptions_prescriptionstatus_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_scan prescriptions_scan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_scan
    ADD CONSTRAINT prescriptions_scan_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_shoefitting prescriptions_shoefitting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_shoefitting
    ADD CONSTRAINT prescriptions_shoefitting_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_shoefitting prescriptions_shoefitting_prescription_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_shoefitting
    ADD CONSTRAINT prescriptions_shoefitting_prescription_id_key UNIQUE (prescription_id);


--
-- Name: prescriptions_template prescriptions_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_template
    ADD CONSTRAINT prescriptions_template_pkey PRIMARY KEY (id);


--
-- Name: prescriptions_weartime prescriptions_weartime_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_weartime
    ADD CONSTRAINT prescriptions_weartime_name_key UNIQUE (name);


--
-- Name: prescriptions_weartime prescriptions_weartime_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_weartime
    ADD CONSTRAINT prescriptions_weartime_pkey PRIMARY KEY (id);


--
-- Name: users_clinic users_clinic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_clinic
    ADD CONSTRAINT users_clinic_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: invoices_invoice_invoice_number_69d5c6a9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoices_invoice_invoice_number_69d5c6a9_like ON public.invoices_invoice USING btree (invoice_number varchar_pattern_ops);


--
-- Name: invoices_invoice_order_id_622235c3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoices_invoice_order_id_622235c3 ON public.invoices_invoice USING btree (order_id);


--
-- Name: invoices_invoice_user_id_05b439b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoices_invoice_user_id_05b439b4 ON public.invoices_invoice USING btree (user_id);


--
-- Name: invoices_invoiceitem_invoice_id_5ce05433; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoices_invoiceitem_invoice_id_5ce05433 ON public.invoices_invoiceitem USING btree (invoice_id);


--
-- Name: orders_order_prescriptions_order_id_2a25823d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_prescriptions_order_id_2a25823d ON public.orders_order_prescriptions USING btree (order_id);


--
-- Name: orders_order_prescriptions_prescription_id_e1a1f543; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_prescriptions_prescription_id_e1a1f543 ON public.orders_order_prescriptions USING btree (prescription_id);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: patients_patient_clinic_id_3ba5a264; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX patients_patient_clinic_id_3ba5a264 ON public.patients_patient USING btree (clinic_id);


--
-- Name: patients_patient_external_id_57f63860_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX patients_patient_external_id_57f63860_like ON public.patients_patient USING btree (external_id varchar_pattern_ops);


--
-- Name: prescriptions_activity_name_4f38791e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_activity_name_4f38791e_like ON public.prescriptions_activity USING btree (name varchar_pattern_ops);


--
-- Name: prescriptions_attachment_prescription_id_8a1f4ded; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_attachment_prescription_id_8a1f4ded ON public.prescriptions_attachment USING btree (prescription_id);


--
-- Name: prescriptions_foottype_name_d02a50f5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_foottype_name_d02a50f5_like ON public.prescriptions_foottype USING btree (name varchar_pattern_ops);


--
-- Name: prescriptions_prescription_activity_level_id_11e0c503; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_activity_level_id_11e0c503 ON public.prescriptions_prescription USING btree (activity_level_id);


--
-- Name: prescriptions_prescription_clinician_id_86deb363; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_clinician_id_86deb363 ON public.prescriptions_prescription USING btree (clinician_id);


--
-- Name: prescriptions_prescription_foot_type_id_d99f6610; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_foot_type_id_d99f6610 ON public.prescriptions_prescription USING btree (foot_type_id);


--
-- Name: prescriptions_prescription_patient_id_22183bec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_patient_id_22183bec ON public.prescriptions_prescription USING btree (patient_id);


--
-- Name: prescriptions_prescription_status_id_dd5f38bf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_status_id_dd5f38bf ON public.prescriptions_prescription USING btree (status_id);


--
-- Name: prescriptions_prescription_template_id_5d26e30d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_template_id_5d26e30d ON public.prescriptions_prescription USING btree (template_id);


--
-- Name: prescriptions_prescription_wear_time_id_80b077c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescription_wear_time_id_80b077c6 ON public.prescriptions_prescription USING btree (wear_time_id);


--
-- Name: prescriptions_prescriptionstatus_name_2109ee8b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_prescriptionstatus_name_2109ee8b_like ON public.prescriptions_prescriptionstatus USING btree (name varchar_pattern_ops);


--
-- Name: prescriptions_scan_prescription_id_c77ce24b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_scan_prescription_id_c77ce24b ON public.prescriptions_scan USING btree (prescription_id);


--
-- Name: prescriptions_weartime_name_298fdb24_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX prescriptions_weartime_name_298fdb24_like ON public.prescriptions_weartime USING btree (name varchar_pattern_ops);


--
-- Name: users_user_clinic_id_4cd2b9d9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_clinic_id_4cd2b9d9 ON public.users_user USING btree (clinic_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoices_invoice invoices_invoice_order_id_622235c3_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoice
    ADD CONSTRAINT invoices_invoice_order_id_622235c3_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoices_invoice invoices_invoice_user_id_05b439b4_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoice
    ADD CONSTRAINT invoices_invoice_user_id_05b439b4_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoices_invoiceitem invoices_invoiceitem_invoice_id_5ce05433_fk_invoices_invoice_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices_invoiceitem
    ADD CONSTRAINT invoices_invoiceitem_invoice_id_5ce05433_fk_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES public.invoices_invoice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order_prescriptions orders_order_prescri_prescription_id_e1a1f543_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order_prescriptions
    ADD CONSTRAINT orders_order_prescri_prescription_id_e1a1f543_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order_prescriptions orders_order_prescriptions_order_id_2a25823d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order_prescriptions
    ADD CONSTRAINT orders_order_prescriptions_order_id_2a25823d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patient patients_patient_clinic_id_3ba5a264_fk_users_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_clinic_id_3ba5a264_fk_users_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.users_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_attachment prescriptions_attach_prescription_id_8a1f4ded_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_attachment
    ADD CONSTRAINT prescriptions_attach_prescription_id_8a1f4ded_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_clinicalmeasure prescriptions_clinic_prescription_id_1f47b9c0_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_clinicalmeasure
    ADD CONSTRAINT prescriptions_clinic_prescription_id_1f47b9c0_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_deviceoption prescriptions_device_prescription_id_3d579c88_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_deviceoption
    ADD CONSTRAINT prescriptions_device_prescription_id_3d579c88_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_intrinsicadjustment prescriptions_intrin_prescription_id_5bcd9573_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_intrinsicadjustment
    ADD CONSTRAINT prescriptions_intrin_prescription_id_5bcd9573_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_materialselection prescriptions_materi_prescription_id_8d1cd850_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_materialselection
    ADD CONSTRAINT prescriptions_materi_prescription_id_8d1cd850_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_offloading prescriptions_offloading_new_prescription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_offloading
    ADD CONSTRAINT prescriptions_offloading_new_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) ON DELETE CASCADE;


--
-- Name: prescriptions_plantermodifier prescriptions_plante_prescription_id_69dcaa79_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_plantermodifier
    ADD CONSTRAINT prescriptions_plante_prescription_id_69dcaa79_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_posting prescriptions_postin_prescription_id_90aae4a3_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_posting
    ADD CONSTRAINT prescriptions_postin_prescription_id_90aae4a3_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_activity_level_id_11e0c503_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_activity_level_id_11e0c503_fk_prescript FOREIGN KEY (activity_level_id) REFERENCES public.prescriptions_activity(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_clinician_id_86deb363_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_clinician_id_86deb363_fk_users_use FOREIGN KEY (clinician_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_foot_type_id_d99f6610_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_foot_type_id_d99f6610_fk_prescript FOREIGN KEY (foot_type_id) REFERENCES public.prescriptions_foottype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_patient_id_22183bec_fk_patients_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_patient_id_22183bec_fk_patients_ FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_status_id_dd5f38bf_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_status_id_dd5f38bf_fk_prescript FOREIGN KEY (status_id) REFERENCES public.prescriptions_prescriptionstatus(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_template_id_5d26e30d_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_template_id_5d26e30d_fk_prescript FOREIGN KEY (template_id) REFERENCES public.prescriptions_template(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_prescription prescriptions_prescr_wear_time_id_80b077c6_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_prescription
    ADD CONSTRAINT prescriptions_prescr_wear_time_id_80b077c6_fk_prescript FOREIGN KEY (wear_time_id) REFERENCES public.prescriptions_weartime(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_scan prescriptions_scan_prescription_id_c77ce24b_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_scan
    ADD CONSTRAINT prescriptions_scan_prescription_id_c77ce24b_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prescriptions_shoefitting prescriptions_shoefi_prescription_id_b1af804f_fk_prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions_shoefitting
    ADD CONSTRAINT prescriptions_shoefi_prescription_id_b1af804f_fk_prescript FOREIGN KEY (prescription_id) REFERENCES public.prescriptions_prescription(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_clinic_id_4cd2b9d9_fk_users_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_clinic_id_4cd2b9d9_fk_users_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.users_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

