# Generated by Django 4.2.21 on 2025-05-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescriptions',
            field=models.ManyToManyField(related_name='orders', to='prescriptions.prescription'),
        ),
    ]
