version: "3.8"

services:
  backend:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --config gunicorn.conf.py
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./:/app
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=core.settings
      - ALLOWED_HOSTS=orthotics.medairum.com,209.97.170.24
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=core.settings
      - ALLOWED_HOSTS=orthotics.medairum.com,209.97.170.24
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./orthotics.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
